name: Base images
on: [push, pull_request]
env:
  DOCKER_CLI_EXPERIMENTAL: 'enabled'
  PUSH: ${{ github.ref == 'refs/heads/main' && '--push' || '' }}
jobs:
  jammy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create build and run images
        run: |
          #!/usr/bin/env bash -euo pipefail
          cd jammy
          set -x
          docker buildx bake --file docker-bake.hcl ${{ env.PUSH }}