name: Base images
on: [push, pull_request]
env:
  DOCKER_CLI_EXPERIMENTAL: 'enabled'
  PUSH: ${{ (github.ref == 'refs/heads/main' && github.event_name != 'pull_request') && '--push' || '' }}
jobs:
  jammy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: jericop/buildpacks-github-actions/setup-tools@add-arm64-support
      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create build and run images
        run: |
          #!/usr/bin/env bash -euo pipefail

          cd jammy
          set -x

          for base_img in build run; do
            for tag in stack target; do
              image_uri="ghcr.io/jericop/${base_img}-jammy"
              
              # Also push `latest` tag based on `target` so stack and new id labels are set
              if [ "$tag" = "target" ]; then
                latest_tag="--tag ${image_uri}:latest"
              else
                latest_tag=
              fi

              docker buildx build \
                --target "${base_img}-cnb-${tag}" \
                --platform linux/amd64 \
                --platform linux/arm64 \
                --tag "${image_uri}:${tag}" \
                $latest_tag \
                ${{ env.PUSH }} \
                .

              # Push platform specific tags (for testing/rebasing purposes)
              for arch_ in amd64 arm64; do
                ddd
                docker pull -q "${image_uri}:${tag}" --platform "linux/${arch_}"
                docker tag "${image_uri}:${tag}" "${image_uri}:${tag}-${arch_}"
                if [ ! -z "${{ env.PUSH }}" ]; then
                  docker push "${image_uri}:${tag}-${arch_}"
                fi
              done
            done
          done
